# PostgreSQL Database

apiVersion: v1
kind: ConfigMap
metadata:
  name: papermerge-database-config
data:
  POSTGRES_DB: papermerge

---
# Worker

apiVersion: v1
kind: ConfigMap
metadata:
  name: papermerge-worker-config
data:
  AWS_ACCESS_KEY_ID: 2e8817266261610810596a50b8f4a8c5
  AWS_REGION_NAME: us-east-1
  AWS_S3_ENDPOINT: http://paperless-minio:9000
  AWS_SECRET_ACCESS_KEY: a503071debfa3ac0c1de1cd79f
  PAPERMERGE__DATABASE__URL: postgresql://papermerge:pmg-secret@papermerge-database:5432/papermerge
  PAPERMERGE__REDIS__URL: redis://papermerge-redis:6379/0
  PAPERMERGE__S3__BUCKET_NAME: papermerge

---
# Worker S3

apiVersion: v1
kind: ConfigMap
metadata:
  name: papermerge-worker-s3-config
data:
  PAPERMERGE__MAIN__MEDIA_ROOT: /var/media/pmg
  S3_WORKER_ARGS: "-Q s3,s3preview -c 2"

---
# Worker OCR

apiVersion: v1
kind: ConfigMap
metadata:
  name: papermerge-worker-ocr-config
data:
  OCR_WORKER_ARGS: "-Q ocr -c 2"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: papermerge-config
data:
  PAPERMERGE__DATABASE__URL: postgresql://papermerge:pmg-secret@papermerge-database:5432/papermerge
  PAPERMERGE__MAIN__MEDIA_ROOT: /var/media/pmg
  PAPERMERGE__OCR__LANG_CODES: "eng,fra"
  PAPERMERGE__OCR__DEFAULT_LANG_CODE: "eng"
  PAPERMERGE__REDIS__URL: redis://papermerge-redis:6379/0
  