# PostgreSQL Database

apiVersion: apps/v1
kind: Deployment
metadata:
  name: papermerge-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: papermerge-database
  template:
    metadata:
      labels:
        app: papermerge-database
    spec:
      containers:
        - name: papermerge-database
          image: postgres:17-alpine
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: papermerge-database-config
            - secretRef:
                name: papermerge-database-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          hostPath:
            path: /data/postgres-data
            type: DirectoryOrCreate