# PostgreSQL Database

apiVersion: apps/v1
kind: Deployment
metadata:
  name: papermerge-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: papermerge-database
  template:
    metadata:
      labels:
        app: papermerge-database
    spec:
      containers:
        - name: papermerge-database
          image: postgres:17-alpine
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: papermerge-database-config
            - secretRef:
                name: papermerge-database-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          hostPath:
            path: /postgres-data
            type: DirectoryOrCreate

---
# Redis Cache

apiVersion: apps/v1
kind: Deployment
metadata:
  name: papermerge-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: papermerge-redis
  template:
    metadata:
      labels:
        app: papermerge-redis
    spec:
      containers:
        - name: papermerge-redis
          image: redis:7-alpine
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 6379

---
# Minio

apiVersion: apps/v1
kind: Deployment
metadata:
  name: papermerge-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: papermerge-minio
  template:
    metadata:
      labels:
        app: papermerge-minio
    spec:
      containers:
        - name: papermerge-minio
          image: minio/minio:latest
          args: ["server", "--console-address", ":9001", "/data"]
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - name: minio-data
              mountPath: /data
          envFrom:
            - secretRef:
                name: papermerge-minio-secret
      volumes:
        - name: minio-data
          hostPath:
            path: /minio-data
            type: DirectoryOrCreate

---
# Worker S3

apiVersion: apps/v1
kind: Deployment
metadata:
  name: papermerge-worker-s3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: papermerge-worker-s3
  template:
    metadata:
      labels:
        app: papermerge-worker-s3
    spec:
      containers:
        - name: papermerge-worker-s3
          image: papermerge/s3worker:0.4.3
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: papermerge-worker-config
            - configMapRef:
                name: papermerge-worker-s3-config
          volumeMounts:
            - name: worker-s3-data
              mountPath: /var/media/pmg
      volumes:
        - name: worker-s3-data
          hostPath:
            path: /data/worker-s3-data
            type: DirectoryOrCreate

---
# Worker OCR

apiVersion: apps/v1
kind: Deployment
metadata:
  name: papermerge-worker-ocr
spec:
  selector:
    matchLabels:
      app: papermerge-worker-ocr
  template:
    metadata:
      labels:
        app: papermerge-worker-ocr
    spec:
      containers:
        - name: papermerge-worker-ocr
          image: papermerge/ocrworker:0.3.1
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          envFrom:
            - configMapRef:
                name: papermerge-worker-config
            - configMapRef:
                name: papermerge-worker-ocr-config

---
# Papermerge

apiVersion: apps/v1
kind: Deployment
metadata:
  name: papermerge
spec:
  selector:
    matchLabels:
      app: papermerge
  template:
    metadata:
      labels:
        app: papermerge
    spec:
      containers:
        - name: papermerge
          image: papermerge/papermerge:3.3.1
          envFrom:
            - configMapRef:
                name: papermerge-config
            - secretRef:
                name: papermerge-secret
          resources:
            limits:
              memory: "1024Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: papermerge-data
              mountPath: /var/media/pmg
      volumes:
        - name: papermerge-data
          hostPath:
            path: /papermerge-data
            type: DirectoryOrCreate
