# PostgreSQL Database

apiVersion: apps/v1
kind: Deployment
metadata:
  name: papermerge-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: papermerge-database
  template:
    metadata:
      labels:
        app: papermerge-database
    spec:
      containers:
        - name: papermerge-database
          image: postgres:17-alpine
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: papermerge-database-config
            - secretRef:
                name: papermerge-database-secret
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
          hostPath:
            path: /data/postgres-data
            type: DirectoryOrCreate

---
# Redis Cache

apiVersion: apps/v1
kind: Deployment
metadata:
  name: papermerge-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: papermerge-redis
  template:
    metadata:
      labels:
        app: papermerge-redis
    spec:
      containers:
        - name: papermerge-redis
          image: redis:7-alpine
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
      volumes:
        - name: redis-data
          hostPath:
            path: /data/redis-data
            type: DirectoryOrCreate

---

# Minio

apiVersion: apps/v1
kind: Deployment
metadata:
  name: papermerge-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: papermerge-minio
  template:
    metadata:
      labels:
        app: papermerge-minio
    spec:
      containers:
        - name: papermerge-minio
          image: minio/minio:latest
          command: [ "minio", "server" ]
          args: [ "--console-address", ":9001", "/data" ]
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - name: minio-data
              mountPath: /data
          envFrom:
            - secretRef:
                name: papermerge-minio-secret
      volumes:
        - name: minio-data
          hostPath:
            path: /data/minio-data
            type: DirectoryOrCreate
