# PostgreSQL Database

apiVersion: v1
kind: Secret
metadata:
  name: papermerge-database-secret
type: Opaque
data:
  POSTGRES_PASSWORD: cG1nLXNlY3JldA==
  POSTGRES_USER: cGFwZXJtZXJnZQ==

---

# Minio

apiVersion: v1
kind: Secret
metadata:
  name: papermerge-minio-secret
type: Opaque
data:
  MINIO_ROOT_USER: MmU4ODE3MjY2MjYxNjEwODEwNTk2YTUwYjhmNGE4YzUK
  MINIO_ROOT_PASSWORD: YTUwMzA3MWRlYmZhM2FjMGMxZGUxY2Q3OWYK
