# PostgreSQL Database

apiVersion: v1
kind: Secret
metadata:
  name: papermerge-database-secret
type: Opaque
data:
  POSTGRES_PASSWORD: cG1nLXNlY3JldA==
  POSTGRES_USER: cGFwZXJtZXJnZQ==

---
# Minio

apiVersion: v1
kind: Secret
metadata:
  name: papermerge-minio-secret
type: Opaque
data:
  MINIO_ROOT_USER: MmU4ODE3MjY2MjYxNjEwODEwNTk2YTUwYjhmNGE4YzUK
  MINIO_ROOT_PASSWORD: YTUwMzA3MWRlYmZhM2FjMGMxZGUxY2Q3OWYK

---
# Papermerge

apiVersion: v1
kind: Secret
metadata:
  name: papermerge-secret
type: Opaque
data:
  PAPERMERGE__AUTH__USERNAME: YWRtaW4=
  PAPERMERGE__AUTH__PASSWORD: c2VjcmV0
  PAPERMERGE__SECURITY__SECRET_KEY: OGFhOTEyN2U5MDQzMjRlMWQ5M2MyYjY4NDgzYTMyN2MzYjViZTk2NGRkMTYxZTNlNGRmOGRiY2EwNDQzZWMyMQ==
