# PostgreSQL Database

apiVersion: v1
kind: Service
metadata:
  name: papermerge-database
spec:
  selector:
    app: papermerge-database
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP