# PostgreSQL Database

apiVersion: v1
kind: Service
metadata:
  name: papermerge-database
spec:
  selector:
    app: papermerge-database
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP

---

# Redis Cache

apiVersion: v1
kind: Service
metadata:
  name: papermerge-redis
spec:
  selector:
    app: papermerge-redis
  ports:
  - port: 6379
    targetPort: 6379
  type: ClusterIP


---
#Minio service

apiVersion: v1
kind: Service
metadata:
  name: papermerge-minio
spec:
  selector:
    app: papermerge-minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
  type: ClusterIP
